pipeline {
    agent  { label 'Ubuntu 22.04' }
    
    environment {
        MYSQL_ROOT_PASSWORD = 'Akki@123%'
        WORDPRESS_DB_NAME = 'wordpressdb'
        WORDPRESS_DB_USER = 'wpuser'
        WORDPRESS_DB_PASSWORD = 'Akki@123%'
        WORDPRESS_DB_HOST = 'localhost'
        WORDPRESS_DIR = '/var/www/sites-enabled'
        DOMAIN_NAME = 'orangetrekkers.site'
        EMAIL_ADDRESS = 'akankshapatil83@gmail.com'
    }
    
    parameters {
        string(name: 'GIT_BRANCH', defaultValue: 'master', description: 'Git branch to build')
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: "${params.GIT_BRANCH}"]], userRemoteConfigs: [[url: 'https://github.com/akankshapatil13/Wordpress-hosting-Project.git']]])
            }
        }
        
        stage('Install Nginx') {
            steps {
                 sh 'sudo apt update'
                 sh 'sudo apt upgrade -y'
                 sh 'sudo apt install -y nginx'
                 sh 'sudo systemctl start nginx'
            }
        }
        
        stage('Install MySQL and secure_installation') {
            steps {
                sh 'sudo apt update'
                sh 'sudo apt install -y mysql-server'
                sh 'sudo systemctl start mysql'

                // Secure MySQL installation
                sh "sudo mysql_secure_installation <<EOF\nY\nY\nY\nY\nEOF"

                // Set strong root password
                sh "mysql -e \"ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '$MYSQL_ROOT_PASSWORD';\""

                // Create WordPress database and user
                sh "mysql -e \"CREATE DATABASE $WORDPRESS_DB_NAME;\""
                sh "mysql -e \"CREATE USER '$WORDPRESS_DB_USER'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '$WORDPRESS_DB_PASSWORD';\""
                sh "mysql -e \"GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_DB_USER'@'localhost';\""
                sh "mysql -e \"FLUSH PRIVILEGES;\""
            }
        }

        stage('Install PHP') {
            steps {
                sh 'sudo apt install -y php php-cli php-fpm php-mysql'
            }
        }

        stage('Download and install WordPress') {
            steps {
                // Download and install WordPress
                sh 'sudo curl -O https://wordpress.org/latest.tar.gz'
                sh 'sudo tar xzvf latest.tar.gz'
                sh 'sudo mv wordpress/* ${WORDPRESS_DIR}'
                sh 'sudo chown -R www-data:www-data ${WORDPRESS_DIR}'
            }
        }
        
        stage('Modify WordPress Configuration') {
            steps {
                dir("${WORDPRESS_DIR}") {
                    sh "sed -i \"/define(\\'DB_NAME\\', \\'.*\\');/a define(\\'SERVER_NAME\\', \\'${DOMAIN_NAME}\\');\" wp-config.php"
                }
            }
        }
    
        stage('Install SSL Certificate') {
            steps {
               sh 'sudo apt install -y certbot python3-certbot-nginx'
               sh "sudo certbot --nginx -d $DOMAIN_NAME -m $EMAIL_ADDRESS --agree-tos -n"
            }
        }
        
        stage('Restart Nginx') {
            steps {
               sh 'sudo systemctl restart nginx'
            }   
        }
    }
}
